version: "3.1"
services:
  db4bix:
    image: vagabondan/db4bix:0.4.10
    build: .
    restart: unless-stopped
    environment:
      - "DEBUG=*"
    volumes:
      - "./config:/app/config"
    networks:
      - db4bix

networks:
  db4bix:

