version: "3.1"
services:
  db4bix:
    image: vagabondan/db4bix
    restart: unless-stopped
    environment:
      - "DEBUG=db4bix:*:info"
    volumes:
      - "./config:/app/config"
    networks:
      - db4bix

networks:
  db4bix:

